schema_version: 1

context:
  name: pyyaml
  version: "6.0.3"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/P/PyYAML/pyyaml-${{ version }}.tar.gz
  sha256: d76623373421df22fb4cf8817020cbb7ef15c725b9d5e45f17e189bfc384190f

build:
  number: 1
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - cython
    - setuptools
    - packaging
    - pip
    - yaml
  run:
    - python >=${{ python_min }}
    - yaml

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - yaml
      pip_check: true

about:
  homepage: http://pyyaml.org/wiki/PyYAML
  license: MIT
  license_file: LICENSE
  summary: YAML parser and emitter for Python
  documentation: http://pyyaml.org/wiki/PyYAML
  repository: https://github.com/yaml/pyyaml

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - ocefpaf
